version: "3"

services:
  #MongoDB
  mongo_db:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      APP_NAME: LearnDocker
      PORT: 3000
      MONGO_URL: mongodb://mongo_db:27017/curd
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
